apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ws-provisioner-perms
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ws-provisioner
subjects:
  - kind: ServiceAccount
    name: ws-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ws-provisioner-perms
