apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ws-provisioner-perms
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ws-provisioner
subjects:
  - kind: ServiceAccount
    name: ws-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ws-provisioner-perms
