access_url: http://gigo.gage.intranet/
logger_id: "prod"
stripe_key: "secret://gigo-stripekey"
storage_config:
  engine: s3
  s3:
    bucket: gigo-core
    region: us-east-1
    access_key: gigo
    secret_key: secret://gigo-corebucket
    endpoint: minio
http_server_config:
  hostname: gigo.gage.intranet
  domain: gage.intranet
  address: "0.0.0.0"
  port: "80"
  development_mode: true
  git_webhook_secret: "secret://gigo-gitwebhook"
  stripe_webhook_secret: "secret://gigo-stripewebhook"
ti_config:
  db_host: "tidb"
  db_port: "4000"
  db_name: "gigo"
  db_user: "gigo"
  db_password: "secret://gigo-tidb"
elastic_config:
  elastic_nodes:
    - "elastic"
  elastic_pass: "secret://gigo-elastic"
redis_config:
  redis_nodes:
    - "redis"
  redis_db: 8
  redis_type: "local"
  redis_pass: "secret://gigo-redis"
node_id: 0
gitea_config:
  host_url: "gitea"
  username: "gigo"
  password: "secret://gigo-gitea"
ws_config:
  host: ws
  port: 45246
derp:
  server:
    enable: true
meili_config:
  host: meili
  token: secret://gigo-meili
  indices:
    posts:
      name: posts
      primary_key: _id
      update_config: false
      searchable_attributes:
        - title
        - description
        - author
      filterable_attributes:
        - languages
        - attempts
        - completions
        - coffee
        - views
        - tags
        - post_type
        - visibility
        - created_at
        - updated_at
        - published
        - tier
        - author_id
      sortable_attributes:
        - attempts
        - completions
        - coffee
        - views
        - created_at
        - updated_at
        - tier
        - _id
    users:
      name: users
      primary_key: _id
      update_config: false
      searchable_attributes:
        - user_name
      sortable_attributes:
        - _id
    tags:
      name: tags
      primary_key: _id
      update_config: false
      searchable_attributes:
        - value
      filterable_attributes:
        - official
      sortable_attributes:
        - _id
        - official
    discussion:
        name: discussion
        primary_key: _id
        update_config: false
        searchable_attributes:
            - body
            - author
            - title
        filterable_attributes:
            - author_id
            - created_at
            - updated_at
            - author_tier
            - awards
            - coffee
            - post_id
            - tags
        sortable_attributes:
            - _id
            - created_at
            - updated_at
            - author_tier
            - coffee
    comment:
        name: comment
        primary_key: _id
        update_config: false
        searchable_attributes:
            - body
            - author
        filterable_attributes:
            - author_id
            - created_at
            - author_tier
            - awards
            - coffee
            - discussion_id
            - lead
        sortable_attributes:
            - _id
            - created_at
            - author_tier
            - coffee
            - lead
    thread_comment:
        name: thread_comment
        primary_key: _id
        update_config: false
        searchable_attributes:
            - body
            - author
        filterable_attributes:
            - author_id
            - created_at
            - author_tier
            - awards
            - coffee
            - discussion_id
            - lead
        sortable_attributes:
            - _id
            - created_at
            - author_tier
            - coffee
            - lead
    workspace_configs:
        name: workspace_configs
        primary_key: _id
        update_config: false
        searchable_attributes:
            - title
            - description
            - content
        filterable_attributes:
            - author_id
            - revision
            - official
            - tags
            - languages
        sortable_attributes:
            - _id
            - revision
            - official
